# Generated by Django 5.2.8 on 2025-11-22 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteAnalisis',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('datos', models.JSONField(default=dict)),
                ('periodo_inicio', models.DateTimeField(blank=True, null=True)),
                ('periodo_fin', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('generado_por', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Reporte de Análisis',
                'verbose_name_plural': 'Reportes de Análisis',
                'ordering': ['-creado_en'],
            },
        ),
    ]
