# Generated by Django 5.2.8 on 2025-12-02 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrusel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrusel',
            name='imagen',
            field=models.ImageField(upload_to='carrusel/'),
        ),
    ]
