# Generated by Django 5.2.8 on 2025-11-22 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero_factura', models.CharField(max_length=100, unique=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('impuestos', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('url_pdf', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
