# Generated by Django 5.2.8 on 2025-11-22 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutIntento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pedido_id', models.BigIntegerField(blank=True, help_text='ID del pedido relacionado (si existe)', null=True)),
                ('metodo_pago', models.CharField(blank=True, max_length=100, null=True)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estado', models.CharField(choices=[('started', 'Iniciado'), ('processing', 'En proceso'), ('failed', 'Fallido'), ('succeeded', 'Exitoso'), ('cancelled', 'Cancelado')], default='started', max_length=30)),
                ('error_mensaje', models.TextField(blank=True, null=True)),
                ('provider_response', models.JSONField(blank=True, help_text='Respuesta raw de la pasarela (paypal/stripe)', null=True)),
                ('session_data', models.JSONField(blank=True, help_text='Datos del proceso (carrito snapshot, metadata)', null=True)),
                ('ip', models.CharField(blank=True, max_length=50, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Intento de Checkout',
                'verbose_name_plural': 'Intentos de Checkout',
            },
        ),
    ]
