# Generated by Django 5.2.8 on 2025-11-22 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checkout_intentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutintento',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='checkoutintento',
            index=models.Index(fields=['usuario'], name='checkout_in_usuario_70272c_idx'),
        ),
        migrations.AddIndex(
            model_name='checkoutintento',
            index=models.Index(fields=['estado'], name='checkout_in_estado_a82dc7_idx'),
        ),
        migrations.AddIndex(
            model_name='checkoutintento',
            index=models.Index(fields=['creado_en'], name='checkout_in_creado__58af4f_idx'),
        ),
    ]
