# Generated by Django 5.2.8 on 2025-11-22 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAccion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(max_length=255)),
                ('modelo_obj', models.CharField(blank=True, help_text='Nombre del modelo al que afectó', max_length=150, null=True)),
                ('objeto_id', models.CharField(blank=True, help_text='ID del objeto afectado', max_length=150, null=True)),
                ('detalle', models.JSONField(blank=True, help_text='Detalles estructurados de la acción', null=True)),
                ('ip', models.CharField(blank=True, max_length=50, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Acción de Admin',
                'verbose_name_plural': 'Acciones de Admin',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=100, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(help_text='grafico, tabla, kpi, etc.', max_length=100)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('orden', models.IntegerField(default=0)),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Widget del Dashboard',
                'verbose_name_plural': 'Widgets del Dashboard',
                'ordering': ['orden'],
            },
        ),
    ]
