# Generated by Django 5.2.8 on 2025-11-22 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('panel_administrador', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adminaccion',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Empleado/Admin que hizo la acción', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='adminaccion',
            index=models.Index(fields=['usuario'], name='panel_admin_usuario_56df5e_idx'),
        ),
        migrations.AddIndex(
            model_name='adminaccion',
            index=models.Index(fields=['modelo_obj'], name='panel_admin_modelo__39a7c2_idx'),
        ),
    ]
