# Generated by Django 5.2.8 on 2025-11-22 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorRegistro',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nivel', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='error', max_length=20)),
                ('mensaje', models.TextField()),
                ('detalle', models.TextField(blank=True, null=True)),
                ('endpoint', models.CharField(blank=True, max_length=255, null=True)),
                ('metodo_http', models.CharField(blank=True, max_length=10, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('resuelto', models.BooleanField(default=False)),
                ('resuelto_en', models.DateTimeField(blank=True, null=True)),
                ('ticket_incidencia', models.CharField(blank=True, help_text='ID en tracker externo (opcional)', max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Registro de Error',
                'verbose_name_plural': 'Registros de Errores',
                'ordering': ['-creado_en'],
            },
        ),
    ]
