# Generated by Django 5.2.8 on 2025-11-22 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('errores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='errorregistro',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='errorregistro',
            index=models.Index(fields=['nivel'], name='errores_err_nivel_a01c3f_idx'),
        ),
        migrations.AddIndex(
            model_name='errorregistro',
            index=models.Index(fields=['creado_en'], name='errores_err_creado__ace81a_idx'),
        ),
    ]
