# Generated by Django 5.2.8 on 2025-11-23 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito_eventos', '0002_initial'),
        ('productos', '0002_alter_producto_imagen1_alter_producto_imagen2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritoevento',
            name='accion',
            field=models.CharField(choices=[('agregar', 'Agregar producto'), ('eliminar', 'Eliminar producto'), ('cambiar_cantidad', 'Cambiar cantidad'), ('vaciar', 'Vaciar carrito')], max_length=50),
        ),
        migrations.AlterField(
            model_name='carritoevento',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.producto'),
        ),
    ]
