# Generated by Django 5.2.8 on 2025-11-22 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioSesion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('inicio_sesion', models.DateTimeField()),
                ('cierre_sesion', models.DateTimeField(blank=True, null=True)),
                ('ip', models.CharField(max_length=50)),
                ('user_agent', models.CharField(max_length=255)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
