# Generated by Django 5.2.8 on 2025-11-22 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('marca', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('stock', models.IntegerField(default=0)),
                ('imagen1', models.CharField(blank=True, max_length=255, null=True)),
                ('imagen2', models.CharField(blank=True, max_length=255, null=True)),
                ('imagen3', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('peso', models.CharField(blank=True, max_length=100, null=True)),
                ('datos_nutricionales', models.TextField(blank=True, null=True)),
                ('ingredientes', models.TextField(blank=True, null=True)),
                ('instrucciones_uso', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categorias.categoria')),
            ],
        ),
    ]
