# Generated by Django 5.2.8 on 2025-11-22 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
