# Generated by Django 5.2.8 on 2025-11-22 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0003_nota_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nota',
            name='producto',
        ),
    ]
