# Generated by Django 5.2.8 on 2025-11-22 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='identificacion',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
